CREATE TABLE IF NOT EXISTS content_categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT UNSIGNED NOT NULL,
  movie_id BIGINT UNSIGNED NULL,
  series_id BIGINT UNSIGNED NULL,
  episode_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_content_category_movie (category_id, movie_id),
  UNIQUE KEY uq_content_category_series (category_id, series_id),
  UNIQUE KEY uq_content_category_episode (category_id, episode_id),
  INDEX idx_content_categories_movie (movie_id),
  INDEX idx_content_categories_series (series_id),
  INDEX idx_content_categories_episode (episode_id),
  CONSTRAINT fk_content_categories_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
  CONSTRAINT fk_content_categories_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
  CONSTRAINT fk_content_categories_series FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE CASCADE,
  CONSTRAINT fk_content_categories_episode FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS content_genres (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  genre_id BIGINT UNSIGNED NOT NULL,
  movie_id BIGINT UNSIGNED NULL,
  series_id BIGINT UNSIGNED NULL,
  episode_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_content_genre_movie (genre_id, movie_id),
  UNIQUE KEY uq_content_genre_series (genre_id, series_id),
  UNIQUE KEY uq_content_genre_episode (genre_id, episode_id),
  INDEX idx_content_genres_movie (movie_id),
  INDEX idx_content_genres_series (series_id),
  INDEX idx_content_genres_episode (episode_id),
  CONSTRAINT fk_content_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE,
  CONSTRAINT fk_content_genres_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
  CONSTRAINT fk_content_genres_series FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE CASCADE,
  CONSTRAINT fk_content_genres_episode FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_content_access (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  movie_id BIGINT UNSIGNED NULL,
  series_id BIGINT UNSIGNED NULL,
  episode_id BIGINT UNSIGNED NULL,
  granted_by_user_id BIGINT UNSIGNED NULL,
  access_type ENUM('owner','granted','temporary') NOT NULL DEFAULT 'granted',
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_content_access_movie (user_id, movie_id),
  UNIQUE KEY uq_user_content_access_series (user_id, series_id),
  UNIQUE KEY uq_user_content_access_episode (user_id, episode_id),
  INDEX idx_user_content_access_user (user_id),
  INDEX idx_user_content_access_movie (movie_id),
  INDEX idx_user_content_access_series (series_id),
  INDEX idx_user_content_access_episode (episode_id),
  INDEX idx_user_content_access_granted_by_user (granted_by_user_id),
  INDEX idx_user_content_access_expires_at (expires_at),
  CONSTRAINT fk_user_content_access_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_content_access_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_content_access_series FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_content_access_episode FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_content_access_granted_by FOREIGN KEY (granted_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS share_links (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  token_hash CHAR(64) NOT NULL,
  movie_id BIGINT UNSIGNED NULL,
  series_id BIGINT UNSIGNED NULL,
  episode_id BIGINT UNSIGNED NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  max_uses INT UNSIGNED NULL,
  used_count INT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME NULL,
  revoked_at DATETIME NULL,
  UNIQUE KEY uq_share_links_token_hash (token_hash),
  INDEX idx_share_links_movie (movie_id),
  INDEX idx_share_links_series (series_id),
  INDEX idx_share_links_episode (episode_id),
  INDEX idx_share_links_created_by_user (created_by_user_id),
  INDEX idx_share_links_active_expires (is_active, expires_at),
  CONSTRAINT fk_share_links_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
  CONSTRAINT fk_share_links_series FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE CASCADE,
  CONSTRAINT fk_share_links_episode FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE CASCADE,
  CONSTRAINT fk_share_links_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS playback_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  session_token_hash CHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  share_link_id BIGINT UNSIGNED NULL,
  media_asset_id BIGINT UNSIGNED NOT NULL,
  movie_id BIGINT UNSIGNED NULL,
  series_id BIGINT UNSIGNED NULL,
  episode_id BIGINT UNSIGNED NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  ended_at DATETIME NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_playback_sessions_token_hash (session_token_hash),
  INDEX idx_playback_sessions_user (user_id),
  INDEX idx_playback_sessions_share_link (share_link_id),
  INDEX idx_playback_sessions_media_asset (media_asset_id),
  INDEX idx_playback_sessions_movie (movie_id),
  INDEX idx_playback_sessions_series (series_id),
  INDEX idx_playback_sessions_episode (episode_id),
  INDEX idx_playback_sessions_expires_at (expires_at),
  CONSTRAINT fk_playback_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_playback_sessions_share_link FOREIGN KEY (share_link_id) REFERENCES share_links(id) ON DELETE SET NULL,
  CONSTRAINT fk_playback_sessions_media_asset FOREIGN KEY (media_asset_id) REFERENCES media_assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_playback_sessions_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE SET NULL,
  CONSTRAINT fk_playback_sessions_series FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE SET NULL,
  CONSTRAINT fk_playback_sessions_episode FOREIGN KEY (episode_id) REFERENCES episodes(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  admin_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_id VARCHAR(64) NULL,
  before_state JSON NULL,
  after_state JSON NULL,
  metadata JSON NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_admin_audit_logs_admin_user (admin_user_id),
  INDEX idx_admin_audit_logs_entity (entity_type, entity_id),
  INDEX idx_admin_audit_logs_action (action),
  INDEX idx_admin_audit_logs_created_at (created_at),
  CONSTRAINT fk_admin_audit_logs_admin_user FOREIGN KEY (admin_user_id) REFERENCES users(id) ON DELETE SET NULL
);
